Bug/removes imageview twice
Sage-Bionetworks/BridgeAppSDK pull request #248
Opened 2017-06-07 23:18 UTC by dephillipsmichael

Fixed minor bug where imageview will get removed twice on return to screen if there is no instruction image

2017-06-07 23:19 UTC, dephillipsmichael commented
@syoung-smallwisdom not sure why i couldn't add you as a reviewer, but this PR is for you

2017-06-08 18:59 UTC, syoung-smallwisdom requested changes

2017-06-08 18:59 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAInstructionStepViewController.swift
> +        else if self.imageView != nil {
If you want to change this to possibly be nil, also change the declaration to optional. Currently, this is defined as *expected* to exist.

````
    @IBOutlet public weak var imageView: UIImageView?
````

2017-06-08 19:05 UTC, dephillipsmichael commented
FTFY @syoung-smallwisdom

2017-06-09 07:39 UTC, syoung-smallwisdom approved these changes
looks good, except you will have merge failures b/c of some changes I made to the instruction step. Sorry about that. Please see if they resolve your issues.

2017-06-10 13:49 UTC, dephillipsmichael commented
This PR is actually not relevant anymore since you made the imageView optional.  :)

2017-06-10 13:49 UTC, closed without merging