Feature/performance
Sage-Bionetworks/BridgeAppSDK pull request #266
Opened 2017-06-25 20:46 UTC by dephillipsmichael

Added performance screen to BridgeAppSDK in a way that is easy to override the UI and functionality of the ViewController

2017-06-26 22:05 UTC, syoung-smallwisdom requested changes
Stopped reviewing. Sorry. 

There is a lot of code here that could use more refactoring and clean up before trying to figure out what is genuinely useful in a shared code base. 

It might be more expedient just to copy/paste into JourneyPro for now and once we have some breathing room, we can look at setting some goals for generalized use.

2017-06-26 22:05 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAAppDelegate.swift
> +        let oneYear = TimeInterval(60 * 60 * 24 * 365)
Use a calendar. This works for 2017 but not 2018. ;)  Also, I'd suggest changing this to DateComponents instead since the rule might be "3 months" etc.

2017-06-26 22:05 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAPerformanceDataSource.swift
> +open class SBAPerformanceDataSource {
I don't really see the value that this class is adding. It's not really a data source b/c it's not a protocol with a concrete implementation.

2017-06-26 22:05 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAPerformanceViewController.swift
> +        for cell in blankPerformanceCells {
blankPerformanceCells?

2017-06-26 22:05 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAPerformanceViewController.swift
> +//        cell.layoutIfNeeded() // <- added to fix bug where user had to scroll before correct autolayout height was calculated
Then why is it commented out? ;)

2017-06-26 22:05 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAPerformanceViewController.swift
> +        return SBAScheduledActivityManager(delegate: self)
Why not use the base class for the default implementation since you don't gain anything from this.  Also, if you refactor `SBABaseScheduledActivityManager` to use a a start/end date rather than daysBehind / daysAhead (deprecate those?) then you can set it up to show you the whole past or a range, as needed.

2017-06-26 22:05 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAPerformanceViewController.swift
> +open class SBAPerformanceViewController: UITableViewController, SBAScheduledActivityManagerDelegate {
I think a better implementation of the architecture for this would be to use a data source that is a protocol with a general-use implementation (extension on  `SBABaseScheduledActivityManager`?). Otherwise, for expediency in getting this to production, you could just get ride of the data source and implement as a part of this controller.

2017-06-26 22:05 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAPerformanceViewController.swift
> +        self.tableView.register(UINib.init(nibName: SBAPerformanceSectionHeader.staticCellName, bundle: Bundle(for: SBAPerformanceSectionHeader.self)), forHeaderFooterViewReuseIdentifier: SBAPerforma
It's one thing to include hardcoded "it only uses this set of magic values" stuff in an app. For a class that is intended to be general-purpose, this kind of thing can make overriding messy. i.e., What happens when someone wants to use a header that inherits from `SBAPerformanceSectionHeader` rather than using the header design included here?

2017-06-26 22:05 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAPerformanceViewController.swift
> +            default: //.completedActivities
Use `.completedActivities` explicitly.

2017-06-26 22:05 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAPerformanceViewController.swift
> +        case .studyProgress:
Break this into a separate method. First, large blocks of nested code is difficult to read (and easy to mess up later). Second, that will allow override.

2017-06-26 22:05 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAPerformanceViewController.swift
> +        }
Um, no. Create a struct with min/max/average and return it in a method that calculates those values for a given activity.

2017-06-26 22:05 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAPerformanceViewController.swift
> +        cell.rightLegendLabel.text = "\(max)"
I take that back. Also, the struct should return a formatter that is appropriate to the data.

2017-06-26 22:05 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAPerformanceViewController.swift
> +        let appDelegate = UIApplication.shared.delegate as! SBAAppDelegate
Danger, Will Robinson! No. Don't do this, please.

2017-06-26 22:05 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAPerformanceViewController.swift
> +        let lengthOfStudyInMonths = (1 + /* +1 for including current month */(monthsYearsBetweenStudyDates.month ?? 0)) + ((monthsYearsBetweenStudyDates.year ?? 0) * 12) // 12 months in a year
Ok, first, if you are using the current calendar and not the Gregorian calendar then you shouldn't assume the number of months is 12. Second, just get the months. oh yeah, and if you used `DateComponents` as suggested above, this can be calculated from that.

2017-06-26 22:05 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAPerformanceViewController.swift
> +        cell.rightLegendLabel.text = monthStrs[month - 1] // - 1 for 0 array indexing
````
let monthFormatter = DateFormatter()
monthFormatter.setLocalizedDateFormatFromTemplate("MMM")
cell.leftLegendLabel.text = monthFormatter.string(from: startDate)
let midDate = calendar.date(byAdding: .month, value: lengthOfStudyInMonths / 2, to: startDate)!
cell.midLegendLabel.text = monthFormatter.string(from: midDate)
cell.rightLegendLabel.text = monthFormatter.string(from: endDate)
````

2017-06-26 22:05 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAPerformanceViewController.swift
> +        cell.linePlotView.progress = Int(Float(lengthOfStudyInMonths) * normalizedValue)
Your comment and the "progress" don't match. There are no `Int` values between 0 and 1.

2017-06-26 22:05 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAPerformanceViewController.swift
> +        formatter.unitsStyle = .full
Where is this used?

2017-06-26 22:05 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAPerformanceViewController.swift
> +        let timeUntilStudyEndsStr = String(format: "%d MONTHS %d DAYS", months, days)
localize

2017-06-26 22:05 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAPerformanceViewController.swift
> +        dateComponents.day = days
Not seeing where the date components is being used, either.

2017-06-26 22:05 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAPerformanceViewController.swift
> +        return attributedString
Localize.

````
let formatter = DateComponentsFormatter()
formatter.maximumUnitCount = 2
formatter.unitsStyle = .full
formatter.allowedUnits = [.year, .month, .day]
let timeUntilStudyEndsStr = formatter.string(from: Date(), to: endDate)?.localizedUppercase ?? ""

let attributedString = NSMutableAttributedString(
    string: timeUntilStudyEndsStr,
    attributes: detailTextAttributes())

var startIndex = 0
let searchString = NSString(string: timeUntilStudyEndsStr)
let length = searchString.length
while startIndex != NSNotFound, startIndex < length {
    let range = searchString.rangeOfCharacter(from: .decimalDigits, options: [], range: NSMakeRange(startIndex, length - startIndex))
    startIndex = range.location + range.length
    if startIndex != NSNotFound {
        attributedString.setAttributes(detailNumberAttributes(), range: range)
    }
}
````

2017-06-26 22:05 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAPerformanceViewController.swift
> +                scores.append(0)
Please change the comment

2017-06-26 22:05 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAPerformanceViewController.swift
> +        return (monthDif.month!, dayDif.day!)
tinker with Playground. This is seriously obfuscated.

2017-06-27 00:06 UTC, dephillipsmichael commented
I agree, at this point I should just add these classes into Journey Pro and continue to iterate on them to make them proper for BASDK.

2017-06-27 00:11 UTC, syoung-smallwisdom commented
groovy

2017-06-29 23:51 UTC, closed without merging