IA-368
Sage-Bionetworks/BridgeAppSDK pull request #313
Opened 2017-08-02 05:13 UTC by joshbruhin

Refactor scrolling to the selected textField when it begins editing so we can scroll to the 'activeTextField' after the keyboard animation. Doing this because the tableView.scrollToRow() function need to be called after the keyboard animation completes because the tableView bounds changes during that animation.

2017-08-07 16:45 UTC, syoung-smallwisdom requested changes
a few nits.

2017-08-07 16:45 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAGenericStepViewController.swift
> +                    fieldCell.textField.isSecureTextEntry = textAnswerFormat.isSecureTextEntry
Should include all functionality of the text answer format:

````
/**
 The autocapitalization type that applies to the user's input.
 By default, the value of this property is `UITextAutocapitalizationTypeSentences`.
 */
@property UITextAutocapitalizationType autocapitalizationType;

/**
 The autocorrection type that applies to the user's input.
 By default, the value of this property is `UITextAutocorrectionTypeDefault`.
 */
@property UITextAutocorrectionType autocorrectionType;

/**
 The spell checking type that applies to the user's input.
 By default, the value of this property is `UITextSpellCheckingTypeDefault`.
 */
@property UITextSpellCheckingType spellCheckingType;

/**
 The keyboard type that applies to the user's input.
 By default, the value of this property is `UIKeyboardTypeDefault`.
 */
@property UIKeyboardType keyboardType;

/**
 Identifies whether the text object should hide the text being entered.
 
 By default, the value of this property is NO.
 */
@property(nonatomic,getter=isSecureTextEntry) BOOL secureTextEntry;
````

2017-08-07 16:45 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAGenericStepViewController.swift
> +//        tableView?.scrollToRow(at: customField.indexPath!, at: .middle, animated: true)
commented out code. please remove.

2017-08-08 03:48 UTC, joshbruhin commented
@syoung-smallwisdom done

2017-08-08 04:13 UTC, syoung-smallwisdom approved these changes

2017-08-08 04:13 UTC, merged