Fix nav view shadow
Sage-Bionetworks/BridgeAppSDK pull request #314
Opened 2017-08-02 15:18 UTC by joshbruhin

Fix bug that prevented the navigation shadow view from showing properly when the tableView has a non-zero contentInset.top

2017-08-07 17:18 UTC, syoung-smallwisdom requested changes
One nit. otherwise, looks good.

2017-08-07 17:18 UTC, syoung-smallwisdom commented on BridgeAppSDK/SBAGenericStepViewController.swift
> +        print("max: " + String(describing: maxY) + ", offset" + String(describing: tableView!.contentOffset.y) )
please remove debug print statement.

2017-08-08 03:49 UTC, joshbruhin commented
@syoung-smallwisdom done

2017-08-08 04:14 UTC, syoung-smallwisdom approved these changes

2017-08-08 04:14 UTC, merged